name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Cargo
        uses: dtolnay/rust-toolchain@stable
      
      - name: Check Format
        run: cargo fmt --check --all
      
      - name: Check Lint
        run: cargo clippy --all -- -D warnings
      
      - name: Build
        run: cargo build

